// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dir_watch_transfer_web.DB;

namespace dirwatchtransferweb.Migrations
{
    [DbContext(typeof(DirWatchTransferContext))]
    [Migration("20190424232324_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("dir_watch_transfer_web.Entity.SymbolicLink", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<bool>("Recursive");

                    b.Property<string>("Source");

                    b.Property<string>("Target");

                    b.Property<bool>("WatchCreationTime");

                    b.Property<bool>("WatchDirectoryName");

                    b.Property<bool>("WatchFileName");

                    b.Property<bool>("WatchLastAccess");

                    b.Property<bool>("WatchLastWrite");

                    b.Property<bool>("WatchSecurity");

                    b.Property<bool>("WatchSize");

                    b.HasKey("ID");

                    b.ToTable("SymbolicLink");
                });
#pragma warning restore 612, 618
        }
    }
}
